<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121028091720 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Player ADD favoriteMurder_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Player ADD CONSTRAINT FK_9FB57F53488532DD FOREIGN KEY (favoriteMurder_id) REFERENCES Murder(id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_9FB57F53488532DD ON Player (favoriteMurder_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Player DROP FOREIGN KEY FK_9FB57F53488532DD");
        $this->addSql("DROP INDEX IDX_9FB57F53488532DD ON Player");
        $this->addSql("ALTER TABLE Player DROP favoriteMurder_id");
    }
}
