<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121028085428 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Game DROP FOREIGN KEY FK_83199EB231CE0272");
        $this->addSql("ALTER TABLE Game ADD CONSTRAINT FK_83199EB231CE0272 FOREIGN KEY (murdererPhoto_id) REFERENCES Photo(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Game DROP FOREIGN KEY FK_83199EB231CE0272");
        $this->addSql("ALTER TABLE Game ADD CONSTRAINT FK_83199EB231CE0272 FOREIGN KEY (murdererPhoto_id) REFERENCES photo(id)");
    }
}
