imports:
    - { resource: config.yml }

parameters:
    admin_password: dc724af18fbdd4e59189f5fe768a5f8311527050

framework:
    test: true
    session:
        storage_id: session.storage.mock_file
