imports:
    - {resource: "security.yml"}

parameters:
    roleLabels:
        ROLE_ADMIN: Admin
        ROLE_PLAYER: Spieler
        ROLE_MURDERER: Mörder

framework:
    secret: %secret%
    charset:         utf-8
    router:          { resource: "%kernel.root_dir%/routing.yml" }
    form:            true
    templating:      { engines: ['twig'] }
    translator:      { fallback: de }
    session:
        default_locale: de
    esi:             { enabled: true }
    validation:      { enable_annotations: true }

assetic:
    read_from:      %project.webdir%
    debug:          false
    use_controller: false
    filters:
        cssrewrite: ~
        compass:
            bin: %path.compass%

doctrine:
    dbal:
        driver:   pdo_mysql
        user:     %mysql.user%
        password: %mysql.password%
        dbname:   %mysql.db%
        port:     %mysql.port%
        host:     %mysql.host%
        charset:  utf8
    orm:
        auto_mapping: true

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

swiftmailer:
    host:      %smtp.host%
    username:  %smtp.username%
    password:  %smtp.password%

webfactory_exceptions:
    bundle: WinkMurderGameBundle
    force: false