imports:
    - {resource: "security.yml"}

parameters:
    flickr_key: e9863e313c7660001d688030a5080de8
    flickr_secret: 3010cce97ff441c9
    flickr_username: winkmurder

framework:
    secret: %secret%
    router:          { resource: "%kernel.root_dir%/routing.yml" }
    form:            true
    templating:      { engines: ['twig'] }
    translator:      { fallback: de }
    default_locale:  de
    esi:             { enabled: true }
    validation:      { enable_annotations: true }
    session:         ~

assetic:
    read_from:      %project.webdir%
    debug:          false
    use_controller: false
    filters:
        cssrewrite: ~
        compass:
            bin: %path.compass%

doctrine:
    dbal:
        driver:   pdo_mysql
        user:     %mysql.user%
        password: %mysql.password%
        dbname:   %mysql.db%
        port:     %mysql.port%
        host:     %mysql.host%
        charset:  utf8
    orm:
        auto_mapping: true
        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%project.libdir%/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                is_bundle: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

webfactory_exceptions:
    bundle: WinkMurderGameBundle
    force: false

stof_doctrine_extensions:
    default_locale: en
    orm:
        default:
            translatable: true