security:
    firewalls:
        admin:
            pattern: ^/administration
            provider: admin
            anonymous: ~
            form_login:
                login_path: /administration/login/
                check_path: /administration/login/check/
                always_use_default_target_path: true
                default_target_path: /administration/
            remember_me:
                name: WinkMurderAdministrator
                key: %secret%
                always_remember_me: true
                lifetime: 31536000
            logout:
                path: /administration/logout/
                target: /administration/login/
        accounts:
            pattern: ^/
            provider: accounts
            anonymous: ~
            remember_me:
                name: WinkMurderPlayer
                key: %secret%
                always_remember_me: true
                lifetime: 31536000
            account:
                login_path: /login/
                check_path: /login/check/
                always_use_default_target_path: true
                default_target_path: /you/

    access_control:
        - { path: ^/administration/login/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/, roles: ROLE_ADMIN }

        - { path: ^/you/, roles: ROLE_PLAYER }
        - { path: ^/investigations/, roles: ROLE_PLAYER }

        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    providers:
        admin:
            memory:
                users:
                    admin: { password: '5b1e4104ab5eda1b3388a68a4621aa04bc5934c1', roles: ROLE_ADMIN }
        accounts:
            entity:
                class: WinkMurderGameBundle:Account
                property: username

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

#    factories:
#        - "%project.srcdir%/WinkMurder/Bundle/GameBundle/Resources/config/security_factory.xml"