security:
    firewalls:
        main:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: /login/
                check_path: /login/check/
                default_target_path: /you/
            remember_me:
                key: %secret%
                always_remember_me: true

    role_hierarchy:
        ROLE_ADMIN: ROLE_PLAYER

    access_control:
        - { path: ^/(css/|favicon.ico|bundles/), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_PLAYER }

    providers:
        accounts:
            entity:
                class: WinkMurder\Bundle\GameBundle\Entity\Account
                property: username
    encoders:
        WinkMurder\Bundle\GameBundle\Entity\AdminAccount: plaintext