security:
    firewalls:
        main:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: /login/
                check_path: /login/check/
                always_use_default_target_path: true
                default_target_path: /
            remember_me:
                key: %secret%
                always_remember_me: true
            account:
                check_path: /login/photo/
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path: /logout/
                target: /login/
                handlers: [wink_murder.logout_handler]

    access_control:
        - { path: ^/(css/|favicon.ico|bundles/), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/, roles: ROLE_ADMIN }
        - { path: ^/set-locale/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: [ROLE_PLAYER, ROLE_ADMIN] }
        - { path: ^/, roles: ROLE_PLAYER }

    providers:
        chain_provider:
            providers: [in_memory, accounts]
        in_memory:
            users:
                admin: { password: '5b1e4104ab5eda1b3388a68a4621aa04bc5934c1', roles: ROLE_ADMIN }
        accounts:
            entity:
                class: WinkMurderGameBundle:Account
                property: username

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    factories:
        - "%project.srcdir%/WinkMurder/Bundle/GameBundle/Resources/config/security_factory.xml"