security:
    firewalls:
        admin:
            pattern: ^/administration
            provider: admin
            anonymous: ~
            form_login:
                login_path: /administration/login/
                check_path: /administration/login/check/
                always_use_default_target_path: true
                default_target_path: /administration/
            remember_me:
                name: WinkMurderAdministrator
                key: %secret%
                always_remember_me: true
                lifetime: 31536000
            logout:
                path: /administration/logout/
                target: /administration/login/
        accounts:
            pattern: ^/
            provider: accountsAndGuest
            anonymous: ~
            remember_me:
                name: WinkMurderPlayer
                key: %secret%
                always_remember_me: true
                lifetime: 31536000
            form_login:
                check_path: /guest-access/login/check/
                always_use_default_target_path: true
                default_target_path: /guest-access/
            account:
                login_path: /login/
                check_path: /login/check/
                always_use_default_target_path: true
                default_target_path: /you/
            logout:
                path: /guest-access/logout/
                target: /guest-access/login/

    access_control:
        - { path: ^/guest-access/login/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/guest-access/, roles: ROLE_GUEST }

        - { path: ^/administration/login/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/, roles: ROLE_ADMIN }

        - { path: ^/you/, roles: ROLE_PLAYER }
        - { path: ^/investigations/, roles: ROLE_PLAYER }

        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    providers:
        admin:
            memory:
                users:
                    admin: { password: %admin_password%, roles: ROLE_ADMIN }
        guest:
            id: wink_murder.guest_user_provider

        accountsAndGuest:
            chain:
                providers: [accounts, guest]

        accounts:
            entity:
                class: WinkMurderGameBundle:Account
                property: username

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
        WinkMurder\Bundle\GameBundle\Security\GuestAccess:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

#    factories:
#        - "%project.srcdir%/WinkMurder/Bundle/GameBundle/Resources/config/security_factory.xml"